server:
  port: ${PORT:8080}
spring:
  application:
    name: homeHub
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: false
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${SECRET}
  expiration: 360 0000